apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# patches:
# - target:
#     kind: Deployment
#     name: orders
#   patch: |-
#     - op: add
#       path: "/spec/template/spec/containers/0/env"
#       value: 
#       - name: QUARKUS_DATASOURCE_ORDERMGMT_DB_JDBC_URL
#         value: jdbc:postgresql://ordermgmt:5432/ordermgmt-db

# - target:
#     kind: Service
#     name: orders
#   patch: |-
#     - op: replace
#       path: /metadata/labels/backstage.io/kubernetes-id
#       value: thegoodcorner-prod